spring:
  profiles:
    active:
      -dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: service-config-client-dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka8761.com:8761/eureka/,http://eureka8762.com:8762/eureka/,http://eureka8763.com:8763/eureka/

---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: service-config-client-test
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka8761.com:8761/eureka/,http://eureka8762.com:8762/eureka/,http://eureka8763.com:8763/eureka/

